# Generated by Django 3.1.5 on 2021-03-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_auto_20210318_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Unknown', 'U'), ('Non-binary', 'NB'), ('Other', 'O')], default='M', max_length=10),
        ),
    ]
