# Generated by Django 3.1.5 on 2021-04-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('account', '0002_email_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('asset_management', '0006_auto_20210401_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
