# Generated by Django 3.1.5 on 2021-04-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='asset_management.role'),
        ),
    ]
