# Generated by Django 3.1.5 on 2021-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0009_auto_20210406_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='maintenance_type',
            field=models.CharField(choices=[('Preventive', 'Prv'), ('Routine', 'Rtn'), ('Inspection', 'Ins'), ('Emergency', 'Emg')], default='Rtn', max_length=10),
        ),
    ]
