# Generated by Django 3.1.5 on 2021-04-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0010_auto_20210428_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('High', 'H'), ('Normal', 'N'), ('Low', 'L'), ('None', 'NO')], default='N', max_length=6),
        ),
    ]
